### ISSUE TITLE
Show number of items in the cart next to the cart icon

### ISSUE THREAD

**Issue by dianezhou96** [dianezhou96/lululedger#11]

**Comment by 0xAl3xH** [comment]
Implemented UI for this, need to have react populate the element with item count

<img width="295" alt="Screen Shot 2023-06-18 at 13 37 31" src="https://github.com/dianezhou96/lululedger/assets/20210402/6ef71b74-feda-41f2-a131-0e35a6ad3395">

**Comment by 0xAl3xH** [comment]
got the react binding set up
