### ISSUE TITLE
Check performance

### ISSUE THREAD

**Issue by dianezhou96** [dianezhou96/lululedger#17]
Optimize DB calls

**Comment by 0xAl3xH** [comment]
We need to figure out why adding to cart takes more than 4 seconds... 

<img width="631" alt="Screen Shot 2023-06-18 at 14 06 58" src="https://github.com/dianezhou96/lululedger/assets/20210402/0c50b077-c4ae-431e-a7ab-c293c1f8408e">

**Comment by dianezhou96** [comment]
Make a new task if anything specific comes up
