### ISSUE TITLE
Add informational toasts on submissions

### ISSUE THREAD

**Issue by dianezhou96** [dianezhou96/lululedger#2]
- Add to cart
- Create new cart
- Create account (maybe this will be an informational screen instead)
- Delete cart
- Edit / delete items in cart (functionality coming soon although not required)
- Invalid credentials

**Comment by 0xAl3xH** [comment]
need to make sure empty cart name is warned/errored

**Comment by dianezhou96** [comment]
There are popconfirm on or input validation on all of these now.
