### ISSUE TITLE
How to close the shop

### ISSUE THREAD

**Issue by dianezhou96** [dianezhou96/lululedger#61]
After deadline, need to prevent post/put requests and disable all forms in the frontend. Add comments and triage later.

**Comment by 0xAl3xH** [comment]
1. use a singles type in db for `shop_open`, defaults to `true`
2. add a middleware that we use in front of all incoming requests to check for either 
    1. the request is an admin
    2. the request is `GET` 
3. profit

**Comment by dianezhou96** [comment]
Copy changes: `Pending submission` > `Canceled`

**Comment by dianezhou96** [comment]
Frontend disable:
- Sign up (button & account form)
- Add to cart (shop)
- Add new cart (cart selector)
- Editing/deleting cart table
